Repository spinframework/runtime-class-manager, pull requests merged in 2024-04, with the labels that each got.

#78 Include node-installer Dockerfile in dependabot config
  .github/dependabot.yml
Labels: area/node-installer, kind/feature

#79 pin docker images
  Dockerfile
  images/installer/Dockerfile
  tilt.dockerfile
Labels: kind/chore, security

#77 Harden GitHub actions
  .github/workflows/container-image.yml
  .github/workflows/helm-chart-release.yml
  .github/workflows/installer-build.yml
  .github/workflows/manager-build.yml
  .github/workflows/sbom.yml
  .github/workflows/sign-image.yml
Labels: area/github_actions, kind/feature, security

#93 update golang.org/x/net to v0.23.0
  go.mod
  go.sum
Labels: area/dependencies, go, security

#80 Add dependency review action
  .github/workflows/dependency-review.yml
Labels: area/github_actions, security

#106 Various fixes
  .github/workflows/ci.yml
  Makefile
  api/v1alpha1/shim_types.go
  config/crd/bases/runtime.kwasm.sh_shims.yaml
  internal/controller/shim_controller.go
Labels: kind/bug
